# Generated by Django 5.1.5 on 2025-03-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_update',
            name='order_id',
            field=models.IntegerField(),
        ),
    ]
